//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Commande_RessourceDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMANDE_RESSOURCE
    {
        public int IdRessource { get; set; }
        public int IdObjet { get; set; }
        public string CheminComplet { get; set; }
        public string NomFichier { get; set; }
        public string ExtFichier { get; set; }
        public string AppParDéfaut { get; set; }
        public string Description { get; set; }
        public int Ordre { get; set; }
        public short Actif { get; set; }
        public string Remarque { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string UserName { get; set; }
        public string UserIP { get; set; }
        public int IdSite { get; set; }
    }
}
