//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Commande_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMANDE
    {
        public int IdCommande { get; set; }
        public string NumCommande { get; set; }
        public string CodeCommande { get; set; }
        public string Description { get; set; }
        public int IdTiers { get; set; }
        public System.DateTime DateCommande { get; set; }
        public int IdSemaineCommande { get; set; }
        public Nullable<System.DateTime> DateExportPrévue { get; set; }
        public int IdSemaineExportPrévue { get; set; }
        public Nullable<System.DateTime> DateExportRéelle { get; set; }
        public int IdSemaineExportRéelle { get; set; }
        public Nullable<System.DateTime> DateLivMatière { get; set; }
        public int IdSemaineLivMatière { get; set; }
        public short IdNote { get; set; }
        public short Annulée { get; set; }
        public short Bloquée { get; set; }
        public short IdEtat { get; set; }
        public short IdStatut { get; set; }
        public short TypeSaisie { get; set; }
        public short ConcernéeParLePlanning { get; set; }
        public string Remarque { get; set; }
        public string Texte1 { get; set; }
        public string Texte2 { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public int Entier1 { get; set; }
        public int Entier2 { get; set; }
        public double Réel1 { get; set; }
        public double Réel2 { get; set; }
        public short Flag0 { get; set; }
        public short Flag1 { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string UserName { get; set; }
        public string UserIP { get; set; }
        public Nullable<System.DateTime> ModifDate { get; set; }
        public int IdSite { get; set; }
    }
}
