//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProPlusNetV2WebServiceDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIERS()
        {
            this.COMMANDE = new HashSet<COMMANDE>();
        }
    
        public int IdTiers { get; set; }
        public string CodeTiers { get; set; }
        public string NomSociété { get; set; }
        public short IdTiersType { get; set; }
        public string Responsable { get; set; }
        public string ResponsableTél { get; set; }
        public string ResponsableMail { get; set; }
        public string Activité { get; set; }
        public int IdMonnaie { get; set; }
        public string Banque { get; set; }
        public string NumCompte { get; set; }
        public string MatriculeFiscal { get; set; }
        public string Registre { get; set; }
        public string Rue { get; set; }
        public string Région { get; set; }
        public string Ville { get; set; }
        public string CodePostal { get; set; }
        public int IdPays { get; set; }
        public string Tél1 { get; set; }
        public string Tél2 { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string URL { get; set; }
        public string Rue_L { get; set; }
        public string Région_L { get; set; }
        public string Ville_L { get; set; }
        public string CodePostal_L { get; set; }
        public int IdPays_L { get; set; }
        public string Tél1_L { get; set; }
        public string Tél2_L { get; set; }
        public string Fax_L { get; set; }
        public string Email_L { get; set; }
        public string URL_L { get; set; }
        public string Rue_F { get; set; }
        public string Région_F { get; set; }
        public string Ville_F { get; set; }
        public string CodePostal_F { get; set; }
        public int IdPays_F { get; set; }
        public string Tél1_F { get; set; }
        public string Tél2_F { get; set; }
        public string Fax_F { get; set; }
        public string Email_F { get; set; }
        public string URL_F { get; set; }
        public string ModeLivraison { get; set; }
        public string ModePayement { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string UserName { get; set; }
        public string UserIP { get; set; }
        public string Déscription { get; set; }
        public string Remarques { get; set; }
        public Nullable<System.DateTime> ModifDate { get; set; }
        public int IdSite { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMANDE> COMMANDE { get; set; }
    }
}
